[effectGenerator21]
Name = "EFFECTGENERATOR_BLOOD_RAIN"
GenerationDelayMin = 0
GenerationDelayMax = 0
GenerationAmount = 5
EffectModel = "EFFECT_BLOOD_HIT"
IgnoreTerrain = 0
SpawnHeight = -1
AccelerationMin = [0,0,0]
AccelerationMax = [0,0,0]
Sound = [0,0]

[effectGenerator22]
Name = "EFFECTGENERATOR_FOUNTAIN"
GenerationDelayMin = 10
GenerationDelayMax = 20
GenerationAmount = 1
EffectModel = "EFFECTELEMENT_WATERDROP"
IgnoreTerrain = 0
SpawnHeight = -1
AccelerationMin = [0,0,0]
AccelerationMax = [0,0,0]
Sound = [0,0]

[effectGenerator23]
Name = "EFFECTGENERATOR_BLOOD_RAIN_BENS_MAP"
GenerationDelayMin = 0
GenerationDelayMax = 0
GenerationAmount = 1
EffectModel = "EFFECT_BLOOD_HIT"
IgnoreTerrain = 0
SpawnHeight = -1
AccelerationMin = [0,0,0]
AccelerationMax = [0,0,0]
Sound = [0,0]

[effectElement121]
Name = "EFFECTELEMENT_ICE_BEAM"
DrawClass = 2
MoveType = 1
Unanimated = 0
Lifespan = [5,5]
AnimationId = 857
SpriteSize = [96,160]
RenderFlags = 1
SpriteSpeed = [85,85]
AnimateOnFloor = true
Unshaded = true
Transparent = 3
MovementFlags = 0
SizeChange = 0
FallAcceleration = 2
InertiaFloor = 0
InertiaAir = 0
SubeffectModel = 0
SubeffectDelay = 0
Movable = false
Impacts = false
TransformModel = 0
LightRadius = 0
LightIntensity = 0
LightFlags = 0
AffectedByWind = 0