[column1054]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]

[column1057]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]

[column1058]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]

[column1062]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]

[column1063]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]

[column1065]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [387, 0, 0, 0, 0, 0, 0, 0]